# -*- coding: utf-8 -*-
"""Kelp2_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pxkHvkl7rUK-t-AEPhoeEAVqsZ0elsX
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import re
from sklearn.preprocessing import MultiLabelBinarizer

sns.set(style="whitegrid")

theme = st.sidebar.radio("🎨 Theme", ["Light", "Dark"])

if theme == "Dark":
    st.markdown("""
        <style>
        .stApp {
            background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
            color: white;
        }
        </style>
    """, unsafe_allow_html=True)
else:
    st.markdown("""
        <style>
        .stApp {
            background: linear-gradient(135deg, #f5f7fa, #c3cfe2);
        }
        </style>
    """, unsafe_allow_html=True)

st.title("📊 Dashboard EDA & IRR - ABSA")

uploaded_file = st.file_uploader("Upload file JSONL", type=["jsonl"])

if uploaded_file:
    data = []
    errors = 0

    lines = uploaded_file.read().decode("utf-8").splitlines()

    for line in lines:
        try:
            data.append(json.loads(line))
        except:
            errors += 1

    df = pd.DataFrame(data)

    st.success(f"Data: {len(df)} baris | Error: {errors}")

    def clean_text(text):
        text = str(text).lower()
        text = re.sub(r'[^a-zA-Z\s]', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    df['clean_text'] = df['text'].apply(clean_text)

    st.subheader("📄 Dataset Preview")
    with st.expander("Lihat Dataset"):
        st.dataframe(df[['text', 'accept']].head(50), use_container_width=True)

    menu = st.sidebar.selectbox(
        "Pilih Analisis",
        ["Distribusi Label", "Distribusi Entitas", "Panjang Review", "Korelasi Label", "NER Viewer"]
    )

    if menu == "Distribusi Label":
        st.subheader("📊 Distribusi Label ABSA")

        labels = df['accept'].dropna().explode()
        label_counts = labels.value_counts().sort_values(ascending=False)

        fig, ax = plt.subplots()
        sns.barplot(x=label_counts.index, y=label_counts.values, ax=ax)

        ax.set_xlabel("Label")
        ax.set_ylabel("Jumlah")
        plt.xticks(rotation=30, ha='right')

        st.pyplot(fig)

        st.markdown("""
        **Insight:**

        Dataset yang digunakan merupakan hasil cleaning sehingga tersisa **678 review**.
        Jumlah ini di bawah standar 800 data, namun dipertahankan untuk menjaga kualitas.

        - Label dominan: **PRODUCT_POSITIVE**
        - Diikuti: **PLACE_POSITIVE**, **PRICE_POSITIVE**
        - Label negatif sangat sedikit

        ➤ Dataset **tidak seimbang (class imbalance)**
        ➤ Model berpotensi bias ke sentimen positif
        """)

    elif menu == "Distribusi Entitas":
        st.subheader("🏷️ Distribusi Entitas")

        entities = []
        for spans in df['spans']:
            if isinstance(spans, list):
                for s in spans:
                    if 'label' in s:
                        entities.append(s['label'])

        entity_counts = pd.Series(entities).value_counts()

        fig, ax = plt.subplots()
        sns.barplot(x=entity_counts.index, y=entity_counts.values, ax=ax)

        plt.xticks(rotation=30, ha='right')
        st.pyplot(fig)

        st.markdown("""
        **Insight:**

        - Dominasi: **PRODUCT_POSITIVE**
        - Diikuti: **PLACE_POSITIVE**, **PRICE_POSITIVE**
        - Entitas lain jauh lebih sedikit

        ➤ Distribusi tidak merata
        ➤ Model sulit belajar entitas minor
        """)

    elif menu == "Panjang Review":
        st.subheader("📏 Distribusi Panjang Review")

        df['length'] = df['clean_text'].apply(lambda x: len(x.split()))

        fig, ax = plt.subplots()
        sns.histplot(df['length'], bins=30, kde=True, ax=ax)

        st.pyplot(fig)

        st.markdown("""
        **Insight:**

        - Mayoritas review pendek–sedang
        - Sedikit yang sangat panjang

        ➤ Cocok untuk model NLP umum
        """)

    elif menu == "Korelasi Label":
        st.subheader("📊 Korelasi Antar Label")

        mlb = MultiLabelBinarizer()
        label_matrix = mlb.fit_transform(df['accept'])

        df_label = pd.DataFrame(label_matrix, columns=mlb.classes_)
        corr = df_label.corr()

        fig, ax = plt.subplots(figsize=(10, 6))
        sns.heatmap(corr, annot=True, cmap='coolwarm', ax=ax)

        st.pyplot(fig)

    # =============================
    # NER VIEWER MULTI COLOR
    # =============================
    elif menu == "NER Viewer":
        st.subheader("🔍 NER Viewer (Slide Data)")

        idx = st.slider("Pilih Index Data", 0, len(df)-1, 0)

        text = df.iloc[idx]['text']
        spans = df.iloc[idx]['spans']

        st.write("### 📝 Text")
        st.write(text)

        st.write("### 🏷️ Entity Highlight")

        # COLOR MAP
        color_map = {
            "PRODUCT": "#1f77b4",
            "PRICE": "#2ca02c",
            "PLACE": "#ff7f0e",
            "PROMOTION": "#9467bd",
            "POSITIVE": "#2ecc71",
            "NEGATIVE": "#e74c3c",
            "NEUTRAL": "#7f8c8d"
        }

        def get_color(label):
            for key in color_map:
                if key in label:
                    return color_map[key]
            return "#95a5a6"

        colored_text = text

        if isinstance(spans, list):
            for span in spans[::-1]:
                start = span['start']
                end = span['end']
                label = span['label']
                color = get_color(label)

                colored_text = (
                    colored_text[:start] +
                    f"<span style='background-color:{color};color:white;padding:4px 8px;border-radius:6px'>"
                    f"{text[start:end]} ({label})</span>" +
                    colored_text[end:]
                )

        st.markdown(colored_text, unsafe_allow_html=True)

        # LEGEND
        st.write("### 🎨 Legend")
        legend_html = ""
        for key, val in color_map.items():
            legend_html += f"<span style='background-color:{val};color:white;padding:6px 12px;margin:5px;border-radius:6px'>{key}</span> "

        st.markdown(legend_html, unsafe_allow_html=True)

st.header("📈 Inter-Annotator Agreement (IRR)")

irr_file = st.file_uploader("Upload IRR JSONL", type=["jsonl"])

if irr_file:
    irr_data = json.load(irr_file)

    df_irr = pd.DataFrame(irr_data).T
    df_irr_summary = df_irr[["kripp_alpha", "percent_agreement", "gwet_ac2"]]

    st.dataframe(df_irr_summary)

    st.markdown("""
    **Insight IRR:**

    - Label positif → agreement tinggi
    - Label netral & negatif → rendah
    - Ada inkonsistensi anotasi

    ➤ Perlu perbaikan guideline anotasi
    """)